export default {
  "fr": {
    jobTitle: "Développeur front-end",
    status: "En mission",
    downloadCV: "Télécharger CV",
    informations: "Informations",
    skills: "Compétences",
    location: "Localisation",
    experience: "Expérience",
    years: "4+ ans",
    availability: "Disponible sous",
    availabilityTime: "1 mois",
    openToFullRemote: "Ouvert au 100% télétravail",
    yes: "Oui",
    aboutMe: "À propos de moi",
    aboutMeText: "Développeur front-end freelance avec plus de 4 ans d'expérience, sensible aux questions d'UX, de performance, de qualité de code et d'accessibilité. J'apprécie le travail en équipe et la formation de développeurs junior. <br>Je recherche actuellement une mission front-end (ou mobile) à Paris flexible sur le télétravail et de préférence dans une petite structure. Je suis ouvert au travail en 4/5ème. <br>Je ne recherche pas de mission sur d'autres langages que JS/TS.",
    resume: "CV",
    products: "Produits",
    experiences: "Expériences",
    frontendDeveloper: "Développeur front-end",
    fullTime: "Temps plein",
    freelance: "Freelance",
    workshopLead: "Workshop Lead",
    timePcd: "Janv. 2021 - <b>Aujourd'hui</b>",
    timeCdcFree: "Août 2020 - Janv. 2021",
    timeCdcCdi: "Avril 2019 - Août 2020",
    cdi: "CDI",
    descriptionPcd: "Aut omnis voluptatem sit sequi. Voluptatem temporibus repellat voluptatem voluptatibus enim voluptas necessitatibus.Aut quasi sunt dolor.Commodi dolores saepe asperiores beatae voluptate corporis est ea voluptatem.Enim quo sed et sint aspernatur distinctio qui quam.",
    descriptionCdcCdi: "Working on the front-end and GraphQL API of dior.com, an isomorphic app entirely written in functional programming and built with React, NextJS, TypeScript, Redux, ApolloGraphQL, recompose, rx-js...",
    timeWagon: 'Déc. 2017 - Nov. 2019',
    descriptionWagon: "Occasionaly leading coding workshops at Le Wagon such as: <br>- Creating a landing page with HTML and CSS<br>- Introduction to JavaScript <br>- Introduction to React",
    timeBluenove: "Sept. 2017 - Avril 2019",
    descriptionBluenove: "Developing Assembl, an Open Source application that enables thousands of people to work together effectively on the definition of new ideas.<br>Assembl's frontend is built with React, Redux, GraphQL, Sass, Jest, flow, webpack...",
    bachelorKinesiology: "Licence en Kinésiologie",
    mastersNeuroscience: "Master en Neurosciences",
    education: "Etudes",
  },
  "en": {
    jobTitle: "Front-end developer",
    status: "Busy",
    downloadCV: "Download CV",
    informations: "Information",
    skills: "Skills",
    location: "Location",
    experience: "Experience",
    years: "4+ years",
    availability: "Availability",
    availabilityTime: "1 month",
    openToFullRemote: "Open to full remote",
    yes: "Yes",
    aboutMe: "About me",
    aboutMeText: "Libero quas veritatis nulla distinctio fuga nihil temporibus et. Quia dicta sapiente qui porro molestiae nobis incidunt voluptatem. Et voluptas sunt nihil. At perferendis voluptatem dolores nulla. Adipisci dolore non. Praesentium ipsa magnam ut quia explicabo voluptates.",
    resume: "CV",
    products: "Products",
    experiences: "Experiences",
    frontendDeveloper: "Front-end developer",
    fullTime: "Full Time",
    freelance: "Freelance",
    workshopLead: "Workshop Lead",
    timePcd: "Jan. 2021 - <b>Present</b>",
    timeCdcFree: "August 2020 - Jan. 2021",
    timeCdcCdi: "April 2019 - August 2020",
    cdi: "Permanent Contract",
    descriptionPcd: "Aut omnis voluptatem sit sequi. Voluptatem temporibus repellat voluptatem voluptatibus enim voluptas necessitatibus.Aut quasi sunt dolor.Commodi dolores saepe asperiores beatae voluptate corporis est ea voluptatem.Enim quo sed et sint aspernatur distinctio qui quam.",
    descriptionCdcCdi: "Working on the front-end and GraphQL API of dior.com, an isomorphic app entirely written in functional programming and built with React, NextJS, TypeScript, Redux, ApolloGraphQL, recompose, rx-js...",
    timeWagon: 'Dec. 2017 - Nov. 2019',
    descriptionWagon: "Occasionaly leading coding workshops at Le Wagon such as: <br>- Creating a landing page with HTML and CSS<br>- Introduction to JavaScript <br>- Introduction to React",
    timeBluenove: "Sept. 2017 - April 2019",
    descriptionBluenove: "Developing Assembl, an Open Source application that enables thousands of people to work together effectively on the definition of new ideas.<br>Assembl's frontend is built with React, Redux, GraphQL, Sass, Jest, flow, webpack...",
    bachelorKinesiology: 'BSc in Kinesiology',
    mastersNeuroscience: "Master's in Neuroscience",
    education: "Education",
  }
}
