export default {
  fr: {
    jobTitle: 'Développeur front-end',
    status: 'En mission',
    downloadCV: 'Télécharger CV',
    informations: 'Informations',
    skills: 'Compétences',
    location: 'Localisation',
    experience: 'Expériences',
    years: '4+ ans',
    availability: 'Disponible sous',
    availabilityTime: '1 mois',
    openToFullRemote: 'Ouvert au 100% télétravail',
    yes: 'Oui',
    aboutMe: 'À propos de moi',
    aboutMeText:
      "Développeur front-end freelance avec plus de 4 ans d'expérience, sensible aux questions d'UX, de performance, de qualité de code et d'accessibilité. J'apprécie le travail en équipe et la formation de développeurs junior. <br>Je recherche actuellement une mission front-end (ou mobile) à Paris et/ou en télétravail, de préférence dans une petite structure.<br> Je suis ouvert au temps partiel.",
    resume: 'CV',
    portfolio: 'Portfolio',
    experiences: 'Expériences',
    frontendDeveloper: 'Développeur front-end',
    fullTime: 'Temps plein',
    freelance: 'Freelance',
    workshopLead: 'Workshop Lead',
    timePcd: "Janv. 2021 - <b>Aujourd'hui</b>",
    timeCdcFree: 'Août 2020 - Janv. 2021',
    timeCdcCdi: 'Avril 2019 - Août 2020',
    cdi: 'CDI',
    descriptionPcd:
      'Aut omnis voluptatem sit sequi. Voluptatem temporibus repellat voluptatem voluptatibus enim voluptas necessitatibus.Aut quasi sunt dolor.Commodi dolores saepe asperiores beatae voluptate corporis est ea voluptatem.Enim quo sed et sint aspernatur distinctio qui quam.',
    descriptionCdcCdi:
      "Développement du front-end et de l'API GraphQL de dior.com, une application isomorphique entièrement écrite en programmation fonctionnelle avec React, NextJS, TypeScript, Redux, Apollo GraphQL, recompose, rx-js...",
    timeWagon: 'Déc. 2017 - Nov. 2019',
    descriptionWagon:
      "Animation ponctuelle de workshops de code tels que : <br>- Création d'une landing page en HTML/CSS<br>- Introduction à JavaScript <br>- Introduction à React",
    timeBluenove: 'Sept. 2017 - Avril 2019',
    descriptionBluenove:
      "Développement d'Assembl, une application open source permettant à des milliers de personnes de travailler efficacement sur la définition de nouvelles idées.<br>Le front-end d'Assemble est développé avec React, Redux, GraphQL, Sass, Jest, flow, webpack...",
    bachelorKinesiology: 'Licence en Kinésiologie',
    mastersNeuroscience: 'Master en Neurosciences',
    education: 'Etudes',
    openToPartTime: 'Ouvert au temps partiel',
    webDevBootcamp: 'Bootcamp en développement web',
    researchAssistant: 'Assistant de recherche au PERFORM Center Sleep Lab',
    languages: 'Langues',
    french: 'Français',
    english: 'Anglais',
    german: 'Allemand',
    portuguese: 'Portugais'
  },
  en: {
    jobTitle: 'Front-end developer',
    status: 'Busy',
    downloadCV: 'Download CV',
    informations: 'Information',
    skills: 'Skills',
    location: 'Location',
    experience: 'Experience',
    years: '4+ years',
    availability: 'Availability',
    availabilityTime: '1 month',
    openToFullRemote: 'Open to full remote',
    yes: 'Yes',
    aboutMe: 'About me',
    aboutMeText:
      "I am a front-end developer with over 4 years of experience. I care about UX, performances, code quality and accessibility. I enjoy teamwork and training junior developers. <br>I'm currently looking for a front-end (or mobile) mission in Paris and/or remotely.<br>I am open to part-time work.",
    resume: 'CV',
    portfolio: 'Portfolio',
    experiences: 'Experiences',
    frontendDeveloper: 'Front-end developer',
    fullTime: 'Full Time',
    freelance: 'Freelance',
    workshopLead: 'Workshop Lead',
    timePcd: 'Jan. 2021 - <b>Present</b>',
    timeCdcFree: 'August 2020 - Jan. 2021',
    timeCdcCdi: 'April 2019 - August 2020',
    cdi: 'Permanent Contract',
    descriptionPcd:
      'Aut omnis voluptatem sit sequi. Voluptatem temporibus repellat voluptatem voluptatibus enim voluptas necessitatibus.Aut quasi sunt dolor.Commodi dolores saepe asperiores beatae voluptate corporis est ea voluptatem.Enim quo sed et sint aspernatur distinctio qui quam.',
    descriptionCdcCdi:
      'Working on the front-end and GraphQL API of dior.com, an isomorphic app entirely written in functional programming and built with React, NextJS, TypeScript, Redux, ApolloGraphQL, recompose, rx-js...',
    timeWagon: 'Dec. 2017 - Nov. 2019',
    descriptionWagon:
      'Occasionaly leading coding workshops at Le Wagon such as: <br>- Creating a landing page with HTML and CSS<br>- Introduction to JavaScript <br>- Introduction to React',
    timeBluenove: 'Sept. 2017 - April 2019',
    descriptionBluenove:
      "Developing Assembl, an Open Source application that enables thousands of people to work together effectively on the definition of new ideas.<br>Assembl's frontend is built with React, Redux, GraphQL, Sass, Jest, flow, webpack...",
    bachelorKinesiology: 'BSc in Kinesiology',
    mastersNeuroscience: "Master's in Neuroscience",
    education: 'Education',
    openToPartTime: 'Open to part time',
    webDevBootcamp: 'Web Development Bootcamp',
    researchAssistant: 'Research Assistant at the PERFORM Center Sleep Lab',
    languages: 'Languages',
    french: 'French',
    english: 'English',
    german: 'German',
    portuguese: 'Portuguese'
  }
};
