export default {
  "fr": {
    jobTitle: "Développeur front-end",
    status: "En mission",
    downloadCV: "Télécharger CV",
    informations: "Informations",
    skills: "Compétences",
    location: "Localisation",
    experience: "Expérience",
    years: "4+ ans",
    availability: "Disponible sous",
    availabilityTime: "1 mois",
    openToFullRemote: "Ouvert au 100% télétravail",
    yes: "Oui",
    aboutMe: "À propos de moi",
    aboutMeText: "Libero quas veritatis nulla distinctio fuga nihil temporibus et. Quia dicta sapiente qui porro molestiae nobis incidunt voluptatem. Et voluptas sunt nihil. At perferendis voluptatem dolores nulla. Adipisci dolore non. Praesentium ipsa magnam ut quia explicabo voluptates.",
    resume: "CV",
    products: "Produits",
    experiences: "Expériences",
    frontendDeveloper: "Développeur front-end",
    fullTime: "Temps plein",
    freelance: "Freelance",
    workshopLead: "Workshop Lead",
    timePcd: "Janv. 2021 - Aujourd'hui",
    timeCdcFree: "Août 2020 - Janv. 2021",
    timeCdcCdi: "Avril 2019 - Août 2020",
    cdi: "CDI",
    descriptionPcd: "Aut omnis voluptatem sit sequi. Voluptatem temporibus repellat voluptatem voluptatibus enim voluptas necessitatibus.Aut quasi sunt dolor.Commodi dolores saepe asperiores beatae voluptate corporis est ea voluptatem.Enim quo sed et sint aspernatur distinctio qui quam.",
    descriptionCdcFree: "Aut omnis voluptatem sit sequi. Voluptatem temporibus repellat voluptatem voluptatibus enim voluptas necessitatibus.Aut quasi sunt dolor.Commodi dolores saepe asperiores beatae voluptate corporis est ea voluptatem.Enim quo sed et sint aspernatur distinctio qui quam.",
    descriptionCdcCdi: "Aut omnis voluptatem sit sequi. Voluptatem temporibus repellat voluptatem voluptatibus enim voluptas necessitatibus.Aut quasi sunt dolor.Commodi dolores saepe asperiores beatae voluptate corporis est ea voluptatem.Enim quo sed et sint aspernatur distinctio qui quam.",
    timeWagon: 'Déc. 2017 - Nov. 2019',
    descriptionWagon: "Aut omnis voluptatem sit sequi. Voluptatem temporibus repellat voluptatem voluptatibus enim voluptas necessitatibus.Aut quasi sunt dolor.Commodi dolores saepe asperiores beatae voluptate corporis est ea voluptatem.Enim quo sed et sint aspernatur distinctio qui quam.",
    timeBluenove: "Sept. 2017 - Avril 2019",
    descriptionBluenove: "Aut omnis voluptatem sit sequi. Voluptatem temporibus repellat voluptatem voluptatibus enim voluptas necessitatibus.Aut quasi sunt dolor.Commodi dolores saepe asperiores beatae voluptate corporis est ea voluptatem.Enim quo sed et sint aspernatur distinctio qui quam.",
    bachelorKinesiology: "Licence en Kinésiologie",
    mastersNeuroscience: "Master en Neurosciences",
    education: "Etudes"
  },
  "en": {
    jobTitle: "Front-end developer",
    status: "Busy",
    downloadCV: "Download CV",
    informations: "Information",
    skills: "Skills",
    location: "Location",
    experience: "Experience",
    years: "4+ years",
    availability: "Availability",
    availabilityTime: "1 month",
    openToFullRemote: "Open to full remote",
    yes: "Yes",
    aboutMe: "About me",
    aboutMeText: "Libero quas veritatis nulla distinctio fuga nihil temporibus et. Quia dicta sapiente qui porro molestiae nobis incidunt voluptatem. Et voluptas sunt nihil. At perferendis voluptatem dolores nulla. Adipisci dolore non. Praesentium ipsa magnam ut quia explicabo voluptates.",
    resume: "CV",
    products: "Products",
    experiences: "Experiences",
    frontendDeveloper: "Front-end developer",
    fullTime: "Full Time",
    freelance: "Freelance",
    workshopLead: "Workshop Lead",
    timePcd: "Jan. 2021 - Present",
    timeCdcFree: "August 2020 - Jan. 2021",
    timeCdcCdi: "April 2019 - August 2020",
    cdi: "Permanent Contract",
    descriptionPcd: "Aut omnis voluptatem sit sequi. Voluptatem temporibus repellat voluptatem voluptatibus enim voluptas necessitatibus.Aut quasi sunt dolor.Commodi dolores saepe asperiores beatae voluptate corporis est ea voluptatem.Enim quo sed et sint aspernatur distinctio qui quam.",
    descriptionCdcFree: "Aut omnis voluptatem sit sequi. Voluptatem temporibus repellat voluptatem voluptatibus enim voluptas necessitatibus.Aut quasi sunt dolor.Commodi dolores saepe asperiores beatae voluptate corporis est ea voluptatem.Enim quo sed et sint aspernatur distinctio qui quam.",
    descriptionCdcCdi: "Aut omnis voluptatem sit sequi. Voluptatem temporibus repellat voluptatem voluptatibus enim voluptas necessitatibus.Aut quasi sunt dolor.Commodi dolores saepe asperiores beatae voluptate corporis est ea voluptatem.Enim quo sed et sint aspernatur distinctio qui quam.",
    timeWagon: 'Dec. 2017 - Nov. 2019',
    descriptionWagon: "Aut omnis voluptatem sit sequi. Voluptatem temporibus repellat voluptatem voluptatibus enim voluptas necessitatibus.Aut quasi sunt dolor.Commodi dolores saepe asperiores beatae voluptate corporis est ea voluptatem.Enim quo sed et sint aspernatur distinctio qui quam.",
    timeBluenove: "Sept. 2017 - April 2019",
    descriptionBluenove: "Aut omnis voluptatem sit sequi. Voluptatem temporibus repellat voluptatem voluptatibus enim voluptas necessitatibus.Aut quasi sunt dolor.Commodi dolores saepe asperiores beatae voluptate corporis est ea voluptatem.Enim quo sed et sint aspernatur distinctio qui quam.",
    bachelorKinesiology: 'BSc in Kinesiology',
    mastersNeuroscience: "Master's in Neuroscience",
    education: "Education"
  }
}
